version: 2
updates:
  # Enable version updates for JavaScript dependencies
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
